# Generated by Django 4.2.20 on 2025-03-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thought',
            options={'ordering': ['-created_at']},
        ),
    ]
